training:
  epochs: 50
  batch_size: 64
  learning_rate: 0.0002
  latent_dim: 100
  generator_hidden_dim: 128
  discriminator_hidden_dim: 128

data:
  raw_data_path: data/raw/
  processed_data_path: data/processed/
  train_split: 0.8
  validation_split: 0.2

logging:
  log_file: logs/training.log
